### ISSUE TITLE
想问下PCB怎么打印

### ISSUE THREAD

**Issue by Bohan-Song** [ParkerLLF/HomeKit-RGB-LightStrip-Controller#1]
我想在嘉立创打印pcb 下载的压缩包里 Gerber_PCB_homekid_Type-C_ESP12_01S.zip是什么文件? 可以直接在嘉立创打印吗? 谢谢

**Comment by Bohan-Song** [comment]
![image](https://user-images.githubusercontent.com/15974667/203682547-cb82c70a-88e4-48f5-b6e3-cbc50762b969.png)


导入是这个样子 然后怎么操作啊  拜托了 感谢

**Comment by ParkerLLF** [comment]
Gerber文件直接下单啊🤣

**Comment by Bohan-Song** [comment]
> 

在嘉立创下单吗? 但是我问嘉立创他们说不支持Gerber文件...
要怎么弄啊 求教

**Comment by ParkerLLF** [comment]
在线计价 直接上传zip文件
![image](https://user-images.githubusercontent.com/29867508/203742568-ce137409-facf-427f-8b0a-5ddfd54c6ddd.png)
![image](https://user-images.githubusercontent.com/29867508/203742816-b072e3b7-8bf8-4463-b515-94a5434d4743.png)

**Comment by Bohan-Song** [comment]
啊 是我搞错了 第一次弄没有经验 非常感谢! 
还想问一下 这里面做出来的PCB是只有一个裸板 没有元器件的是吧?

**Comment by ParkerLLF** [comment]
是的 只有电路板，要贴元件的话 要下SMT贴片订单，比较贵，我都是手工焊的，你第一次搞怕是有点恼火哦，烧录这些你会吗😰

**Comment by Bohan-Song** [comment]
焊接烧录都会  没问题的 我就是没弄过PCB想自己试一下 感谢哦

**Comment by ParkerLLF** [comment]
那行哦 反正贴片不好焊，typeC是噩梦，元件清单你去homekidd的里面看一下https://www.pcbway.com/project/shareproject/Apple_HomeKit_ESP8266_WS2812FX_USB_Type_C_Driver.html
![28184b52bc59be4b53317fe58ca89ec](https://user-images.githubusercontent.com/29867508/203751562-26571342-7ea7-427c-a479-71b17bb22ccf.jpg)

**Comment by ParkerLLF** [comment]
上面是我后面搞得更新的版本 大同小异

**Comment by Bohan-Song** [comment]
黑色真帅啊 你这个全套下来大概多少钱

**Comment by Bohan-Song** [comment]
对了 我用Altium Designer能打开你这个PCB吗 我想改一下文字 (是不是叫丝印)

**Comment by ParkerLLF** [comment]
改丝印的话 我没有放源文件的嘛，PCB是嘉立创免费打样 ，8266 9块 其他的小原件我家里很多，单买也就一两块好几十个，成本就十五块左右

**Comment by ParkerLLF** [comment]
我不知道AD能不能打开Gerber，我还没有用转AD

**Comment by Bohan-Song** [comment]
那你是用啥设计的这个PCB?

**Comment by ParkerLLF** [comment]
嘉立创哈哈哈，也是现学现卖

**Comment by Bohan-Song** [comment]
不知道我描述清楚没有 我不太懂 就是想看看怎么能改一下😂

**Comment by Bohan-Song** [comment]
好的好的

**Comment by ParkerLLF** [comment]
你会画板子的话 我把原理图给你 ，原理图也是我看着homekid的一点点抄板的🤣🤣🤣🤣

**Comment by ParkerLLF** [comment]
主要是我不知道AD能不能打开嘉立创的项目文件，嘉立创的是json，离谱

![image](https://user-images.githubusercontent.com/29867508/203755559-fc0c9b61-8f77-4df0-9778-1d89c731c960.png)

**Comment by Bohan-Song** [comment]
> 你会画板子的话我把原理图给你，原理图也是我看homekid的一点画板的🤗🤗🤗🤗

会的会的 给我吧 感谢哦

**Comment by ParkerLLF** [comment]
![image](https://user-images.githubusercontent.com/29867508/204124072-c413e35a-ce13-4d93-9a55-0925ecdc4877.png)

**Comment by Bohan-Song** [comment]
老哥你这还有没有成品我想买

**Comment by ParkerLLF** [comment]
你在咸鱼搜索用户“ParkerLLF”，我挂了一些，也重新搞了3D打印外壳
